repository: "tbates/Multivariate-Stats-Course"
url: "https://tbates.github.io/"
# Note - if you enable this, use jekyll --baseurl '/' to view locally
baseurl: "/Multivariate-Stats-Course"

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Factor analysis and Path diagrams!
# Short description (goes below the title; it will also be used in the RSS feed)
description: "Lectures on multivariate statistics, factor analysis and Structural Equation Modeling"

gems:
  - jekyll-feed

